version: '3'
services:
  app:
    image: node:20.5
    container_name: app_main
    restart: always
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - ./db:/database/data
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: s-group
    ports:
      - 3318:3306
    container_name: app_db
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          interval: 30s
          timeout: 10s
          retries: 5
    networks:
      - app-network
  redis:
    image: redis
    container_name: app_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - app-network
  nginx:
    image: nginx:1.19
    container_name: app_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network    
networks:
  app-network:
    driver: bridge

