version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - ./db:/database/data
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: s-group
    ports:
      - 3318:3306
    container_name: app_db
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          interval: 30s
          timeout: 10s
          retries: 5
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

